Repository internxt/drive-server-wip, pull requests merged in 2023-08, with the labels that each got.

#177 [PB-544]: feat/get items from private sharing
  migrations/20230820040504-private-sharing-role.js
  migrations/20230820040539-private-sharing-permission.js
  migrations/20230820040557-private-sharing-folder-role.js
  src/lib/jwt.ts
  src/modules/file/file.module.ts
  src/modules/file/file.repository.ts
  src/modules/folder/folder.domain.ts
  src/modules/folder/folder.module.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/private-share-folder/private-sharing.controller.ts
  src/modules/private-share-folder/private-sharing.module.ts
  src/modules/private-share-folder/private-sharing.repository.ts
  src/modules/private-share-folder/private-sharing.usecase.spec.ts
  src/modules/private-share-folder/private-sharing.usecase.ts
  src/modules/private-share-folder/private-sharring.usecase.spec.ts
  src/modules/user/user.module.ts
  test/share.mother.ts
  test/user.mother.ts
Labels: enhancement

#186 [PB-531 PB-652]: feat/create private sharing and store owner encrypted encryption key
  migrations/20230619014713-create-private-sharing-folder-table.js
  src/modules/folder/folder.usecase.ts
  src/modules/private-share-folder/dto/create-private-sharing.dto.ts
  src/modules/private-share-folder/private-sharing.controller.ts
  src/modules/private-share-folder/private-sharing.module.ts
  src/modules/private-share-folder/private-sharing.repository.ts
  src/modules/private-share-folder/private-sharing.usecase.spec.ts
  src/modules/private-share-folder/private-sharing.usecase.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.ts
  src/shared-workspace/shared-workspace.module.ts
Labels: enhancement

#189 [PB-651]: feat/get invited users to shared folder
  src/modules/private-share-folder/private-sharing-folder.model.ts
  src/modules/private-share-folder/private-sharing.controller.ts
  src/modules/private-share-folder/private-sharing.repository.ts
  src/modules/private-share-folder/private-sharing.usecase.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.ts
Labels: enhancement

#175 [PB-542]: feat/update private key re encrypted
  src/modules/auth/jwt.strategy.ts
  src/modules/keyserver/key-server.repository.ts
  src/modules/user/dto/update-password.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.ts
Labels: enhancement

#192 [PB-620 PB-659]: feat/stop-remove sharing
  src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
  src/modules/private-share-folder/private-sharing.controller.ts
  src/modules/private-share-folder/private-sharing.module.ts
  src/modules/private-share-folder/private-sharing.repository.ts
  src/modules/private-share-folder/private-sharing.usecase.spec.ts
  src/modules/private-share-folder/private-sharing.usecase.ts
Labels: enhancement

#194 [_]: fix/same format getting items and shared folders
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/private-share-folder/dto/get-items-and-shared-folders.dto.ts
  src/modules/private-share-folder/private-sharing-folder.domain.ts
  src/modules/private-share-folder/private-sharing-folder.model.ts
  src/modules/private-share-folder/private-sharing.controller.ts
  src/modules/private-share-folder/private-sharing.repository.ts
  src/modules/private-share-folder/private-sharing.usecase.spec.ts
  src/modules/private-share-folder/private-sharing.usecase.ts
Labels: enhancement, mod: private-sharing

#196 [_]: refactor/testing-framework
  .github/workflows/sonar-analysis.yml
  package.json
  sonar-project.properties
  src/modules/private-share-folder/private-sharing.usecase.spec.ts
  test/fixtures.spec.ts
  test/fixtures.ts
  test/share.mother.ts
  test/user.mother.ts
  yarn.lock
Labels: enhancement

#200 [_]: feat/private-sharing-indexes
  migrations/20230818075304-private-sharing-indexes.js
Labels: enhancement

#205 [PB-118]: advanced-sharing
  migrations/20230828095420-create-roles-table.js
  migrations/20230828095421-create-permissions-table.js
  migrations/20230828095422-create-sharings-table.js
  migrations/20230828095430-create-sharing-roles-table.js
  migrations/20230828095502-create-sharing-invites-table.js
  src/app.module.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.ts
  src/modules/sharing/dto/accept-invite.dto.ts
  src/modules/sharing/dto/create-invite.dto.ts
  src/modules/sharing/dto/create-sharing-role.dto.ts
  src/modules/sharing/dto/get-items-and-shared-folders.dto.ts
  src/modules/sharing/dto/update-sharing-role.dto.ts
  src/modules/sharing/models/index.ts
  src/modules/sharing/models/sharing-roles.model.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.domain.ts
  src/modules/sharing/sharing.module.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/sharing/sharing.service.ts
  src/modules/user/user.usecase.ts
Labels: enhancement

#206 [PB-919] Feat/Allow remove user from shared folder by himself
  migrations/20230828095420-create-roles-table.js
  migrations/20230829075304-private-sharing-indexes.js
  seeders/20230620032601-roles.js
  seeders/20230620032717-permissions.js
  src/modules/private-share-folder/private-sharing.controller.ts
  src/modules/private-share-folder/private-sharing.usecase.spec.ts
  src/modules/private-share-folder/private-sharing.usecase.ts
  src/modules/sharing/models/index.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
  test/fixtures.ts
Labels: enhancement, mod: advanced-sharing
