Repository internxt/drive-server-wip, pull requests merged in 2024-10, with the labels that each got.

#403 [IN-79]: fix/cleanup-files-name-indexes
  migrations/20241001112638-drop-name-indexes-files.js
  migrations/20241001115355-script-to-remove-plain-name-duplicates-files.js
  migrations/20241001120044-create-index-plainname-folderid-type-exists-unique-files.js
Labels: enhancement, ready-for-preview

#404 [_] fix: update last password changed at on password change
  src/modules/user/user.usecase.ts
Labels: bug, ready-for-preview

#401 [PB-3009]: feat/creation modification times on folders
  migrations/20240927193342-add-modification-creation-times-to-folders.js
  migrations/20241002040050-create-modificationtime-index-on-files.js
  migrations/20241002044035-create-modificationtime-index-on-folders.js
  src/modules/file/dto/create-file.dto.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/dto/create-folder.dto.ts
  src/modules/folder/folder.attributes.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.domain.ts
  src/modules/folder/folder.model.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/share/share.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#405 [_] fix: return tokens on password change
  src/modules/user/user.controller.ts
Labels: bug, ready-for-preview

#387 [PB-2865] feat: add support for sharings and multiple teams
  src/modules/sharing/guards/sharings-token.interface.ts
  src/modules/sharing/models/index.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.repository.spec.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
  src/modules/workspaces/dto/get-shared-items.dto.ts
  src/modules/workspaces/dto/shared-with.dto.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview, workspaces

#407 [PB-3045]: fix/get-ancestors-in-workspace
  migrations/20241004142347-get-folder-ancestor-omit-root-children.js
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: bug, ready-for-preview, workspaces

#408 [PB-3057]: feat/allow sorting workspaces trash
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.usecase.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview, workspaces

#411 [_]: fix/retrun user's root folder when retrieving ancestors in workspaces
  migrations/20241018040841-modify-get-folder-ancestor-omit-root-children-function.js
  src/modules/auth/decorators/workspace.decorator.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.spec.ts
  src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
Labels: ready-for-preview, workspaces

#410 [PB-2217]: feat/get-item-by-path
  migrations/20241007154046-add-find-folder-by-path-function.js
  src/lib/path.spec.ts
  src/lib/path.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: ready-for-preview

#415 [_]: fix/restore old folders/existence GET with query param
  src/modules/folder/dto/folder-existence-in-folder-old.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
Labels: bug, ready-for-preview

#416 [_] fix: return body decorator to existence POST
  src/modules/folder/folder.controller.ts
Labels: bug, ready-for-preview

#412 [PB-2347]: feat/assign free storage to owner
  migrations/20241029132704-update--workspace-owners-space-limit.js
  src/modules/workspaces/domains/workspaces.domain.ts
  src/modules/workspaces/dto/create-workspace-invite.dto.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview, workspaces

#414 [PB-3215]: feat/modify members storage
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/gateway/gateway.usecase.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview, workspaces

#419 [PB-3046]: feat/implement fuzzy search functionality within workspaces
  src/modules/fuzzy-search/fuzzy-search.module.ts
  src/modules/fuzzy-search/fuzzy-search.usecase.spec.ts
  src/modules/fuzzy-search/fuzzy-search.usecase.ts
  src/modules/fuzzy-search/look-up.model.ts
  src/modules/fuzzy-search/look-up.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.module.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview, workspaces
