Repository internxt/drive-server-wip, pull requests merged in 2024-01, with the labels that each got.

#251 Change user email: handle user not found and user email already in used exceptions
  src/modules/user/exception/referral-not-found.exception.ts
  src/modules/user/exception/referrals-not-available.exception.ts
  src/modules/user/exception/user-email-already-in-use.exception.ts
  src/modules/user/exception/user-not-found.exception.ts
  src/modules/user/exception/user-referral-not-found.exception.ts
  src/modules/user/exception/user.exception.ts
  src/modules/user/user.usecase.ts
Labels: enhancement

#252 [PB-1483]: fix/decode sharing password header
  src/modules/sharing/sharing.controller.ts
Labels: bug

#254 Chore: remove middleware logger for production environment
  src/main.ts
Labels: enhancement

#148 [WT-340]: Feat/Add lastPasswordChangeAt to users
  migrations/20240109071854-add-lastPasswordChangedAt-to-users.js
  src/externals/bridge/bridge.service.spec.ts
  src/lib/jwt.ts
  src/modules/auth/jwt.strategy.spec.ts
  src/modules/auth/jwt.strategy.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/folder/folder.e2e.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/send/send.usecase.spec.ts
  src/modules/share/share.usecase.spec.ts
  src/modules/trash/trash.usecase.spec.ts
  src/modules/user/user.attributes.ts
  src/modules/user/user.domain.ts
  src/modules/user/user.model.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.ts
Labels: enhancement, stalled

#261 fix: handle workspace users on email change
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: bug

#259 [PB-845]: feat/calculate-folder-size
  src/common/base-http.exception.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/folder/exception/calculate-folder-size-timeout.exception.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/send/send.usecase.spec.ts
  src/modules/share/share.usecase.spec.ts
  src/modules/trash/trash.usecase.spec.ts
Labels: enhancement

#262 chore/use automock for missing dependencies in unit tests
  src/modules/file/file.usecase.spec.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/send/send.usecase.spec.ts
  src/modules/share/share.usecase.spec.ts
  src/modules/trash/trash.usecase.spec.ts
  src/modules/user/user.usecase.spec.ts
Labels: enhancement

#250 [PB-1402]: feat/auto account unblock
  .env.template
  migrations/20240117140256-add-unblock-account-to-mailtype-enum.js
  src/config/configuration.ts
  src/externals/mailer/mailer.service.ts
  src/lib/time.spec.ts
  src/lib/time.ts
  src/modules/security/mail-limit/mail-limit.domain.ts
  src/modules/security/mail-limit/mail-limit.model.ts
  src/modules/security/mail-limit/mail-limit.repository.ts
  src/modules/security/mail-limit/mailTypes.ts
  src/modules/security/security.module.ts
  src/modules/user/dto/account-unblock.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.domain.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: enhancement

#264 [PB-845]: feat/Calculate-sharing-folder-size
  src/common/uuid.dto.spec.ts
  src/common/uuid.dto.ts
  src/modules/sharing/exception/sharing-not-found.exception.ts
  src/modules/sharing/exception/sharing.exception.ts
  src/modules/sharing/sharing.controller.spec.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
Labels: enhancement
