Repository internxt/drive-server-wip, pull requests merged in 2024-03, with the labels that each got.

#276 [IN-31] ci: add needed actions
  .github/workflows/build-and-publish-preview.yml
  .github/workflows/deploy-pr-preview.yml
  .github/workflows/dispatch-cleanup-pr-preview.yml
  .github/workflows/slash-command-dispatcher.yaml
  infrastructure/preview.Dockerfile
Labels: preview

#283 [PB-1768]: Feat/Move file & folders by UUID
  src/modules/feature-limit/feature-limit-migration.service.ts
  src/modules/feature-limit/feature-limit.module.ts
  src/modules/file/dto/move-file.dto.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/dto/move-folder.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/sharing/dto/get-items-and-shared-folders.dto.ts
  src/modules/sharing/sharing.module.ts
Labels: enhancement, ready-for-preview

#291 [_] feat: workspace role guard
  src/modules/workspaces/domains/workspace-team-user.domain.ts
  src/modules/workspaces/domains/workspace-team.domain.ts
  src/modules/workspaces/domains/workspace-user.domain.ts
  src/modules/workspaces/domains/workspaces.domain.ts
  src/modules/workspaces/guards/workspace-required-access.decorator.ts
  src/modules/workspaces/guards/workspaces.guard.spec.ts
  src/modules/workspaces/guards/workspaces.guard.ts
  src/modules/workspaces/models/workspace-team-users.model.ts
  src/modules/workspaces/models/workspace.model.ts
  src/modules/workspaces/repositories/team.repository.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.module.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#277 [PB-1740]: feat/add items to trash by uuid
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/trash/dto/controllers/move-items-to-trash.dto.spec.ts
  src/modules/trash/dto/controllers/move-items-to-trash.dto.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.controller.ts
Labels: ready-for-preview
