Repository internxt/drive-server-wip, pull requests merged in 2024-09, with the labels that each got.

#389 [PB-2770] fix: check file existence with name encrypted backend side
  src/modules/file/dto/create-file.dto.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: bug, ready-for-preview

#390 [PB-2763] fix: add webhooks notifications on storage changes
  src/externals/notifications/events/notification.event.ts
  src/externals/notifications/listeners/notification.listener.ts
  src/externals/notifications/notifications.module.ts
  src/externals/notifications/storage.notifications.service.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.module.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.module.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.controller.ts
  src/modules/trash/trash.module.ts
Labels: bug, enhancement, ready-for-preview

#391 [_] chore: removed event handled log
  src/externals/notifications/listeners/notification.listener.ts
Labels: ready-for-preview

#392 Feat/apn service
  .env.template
  src/config/configuration.ts
  src/externals/apn/apn.module.ts
  src/externals/apn/apn.service.ts
  src/externals/apn/apn.types.ts
  src/externals/notifications/notifications.module.ts
  src/externals/notifications/storage.notifications.service.ts
  src/modules/user/user.repository.ts
Labels: enhancement, ready-for-preview

#393 feat: look for existent files with array
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/dto/files-existence-in-folder.dto.spec.ts
  src/modules/folder/dto/files-existence-in-folder.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
Labels: enhancement

#395 feat: allow existent folder by plainName
  src/modules/folder/dto/folder-existence-in-folder.dto.spec.ts
  src/modules/folder/dto/folder-existence-in-folder.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: ready-for-preview

#396 [PB-2376] fix: added pagination query param to get folder content
  src/common/dto/basic-pagination.dto.spec.ts
  src/common/dto/basic-pagination.dto.ts
  src/common/dto/uuid.dto.spec.ts
  src/common/dto/uuid.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/sharing/sharing.controller.spec.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/workspaces/workspaces.controller.ts
Labels: enhancement, ready-for-preview

#394 [PB-2628, BR-492]: fix/Improve file search ranking
  src/modules/fuzzy-search/look-up.repository.ts
Labels: bug, ready-for-preview

#397 [PB-2946]: feat/update trash controller to support sorting
  src/modules/trash/trash.controller.ts
Labels: enhancement, ready-for-preview

#398 [PB-2973, PB-2974]: fix/replace-spaces-by-the-&-operator-when-searching
  src/modules/fuzzy-search/look-up.repository.ts
Labels: bug

#400 [_] fix: align new file endpoint with old drive-server implementation
  src/modules/file/dto/create-file.dto.ts
  src/modules/file/file.usecase.ts
Labels: bug, ready-for-preview
