Repository internxt/drive-server-wip, pull requests merged in 2024-05, with the labels that each got.

#302 [_]: Fix/Reverts enforce id type when listing metadata
  src/modules/folder/folder.controller.ts
Labels: bug, ready-for-preview

#299 [PB-1842]: feat/workspaces-members List workspace members with their information
  src/modules/user/dto/user-to-json.dto.ts
  src/modules/user/user.domain.ts
  src/modules/workspaces/attributes/workspace-users.attributes.ts
  src/modules/workspaces/domains/workspace-user.domain.ts
  src/modules/workspaces/dto/workspace-user-member.dto.ts
  src/modules/workspaces/repositories/team.repository.spec.ts
  src/modules/workspaces/repositories/team.repository.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#307 feat: remove workspace invite
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#308 feat: modified workspace creation flow
  src/modules/gateway/dto/initialize-workspace.dto.ts
  src/modules/gateway/gateway.usecase.ts
  src/modules/workspaces/dto/setup-workspace.dto.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#311 [PB-2022]: Feat/Invited meet users can join calls
  migrations/20240513092428-add-room-to-meet-beta-users.js
  src/lib/jitsi.ts
  src/lib/jwt.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#313 [_]: fix/sort-files-by-name-using-natural-order
  migrations/20240515091404-create-custom-collation.js
  src/modules/file/file.repository.ts
  src/modules/folder/folder.controller.ts
Labels: bug, ready-for-preview

#300 [PB-1843, PB-1840] feat: added deactivate user and member details endpoint
  src/modules/workspaces/repositories/team.repository.spec.ts
  src/modules/workspaces/repositories/team.repository.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#315 [_]: Fix/Add parent uuid to intial folders
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#309 [PB-2090, PB-2091, PB-2103] feat: create files and folders in personal workspaces
  migrations/20240311202510-create-workspace-default-team-fk.js
  migrations/20240311203000-create-workspace-users-table.js
  migrations/20240311203014-create-workspace-items-user-table.js
  migrations/20240319130531-create-workspace-invites-table.js
  migrations/20240512231209-add-root-folder-id-to-workspace-table.js
  migrations/20240513001039-add-root-folder-id-to-workspace-user-table.js
  src/modules/file/dto/create-file.dto.ts
  src/modules/file/file.model.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/exception/invalid-parent-folder.ts
  src/modules/folder/folder.model.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/workspaces/attributes/workspace-items-users.attributes.ts
  src/modules/workspaces/attributes/workspace-users.attributes.ts
  src/modules/workspaces/attributes/workspace.attributes.ts
  src/modules/workspaces/domains/workspace-item-user.domain.ts
  src/modules/workspaces/domains/workspace-user.domain.ts
  src/modules/workspaces/domains/workspaces.domain.ts
  src/modules/workspaces/dto/create-workspace-file.dto.ts
  src/modules/workspaces/dto/create-workspace-folder.dto.ts
  src/modules/workspaces/dto/pagination.dto.ts
  src/modules/workspaces/models/workspace-items-users.model.ts
  src/modules/workspaces/models/workspace-users.model.ts
  src/modules/workspaces/models/workspace.model.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.module.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#318 [_] Feat/add get workspace credentials
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: ready-for-preview

#321 [_] chore: bigint variables are now handled with number
  src/modules/workspaces/attributes/workspace-invite.attribute.ts
  src/modules/workspaces/attributes/workspace-users.attributes.ts
  src/modules/workspaces/domains/workspace-invite.domain.ts
  src/modules/workspaces/domains/workspace-user.domain.ts
  src/modules/workspaces/dto/workspace-user-member.dto.ts
  src/modules/workspaces/models/workspace-invite.model.ts
  src/modules/workspaces/models/workspace-users.model.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: bug, ready-for-preview

#305 [PB-2081]: feat/edit basic workspace details
  src/modules/workspaces/dto/edit-workspace-details-dto.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#310 [_] feat: workspaces enable endpoints to retrieve invitations
  src/modules/user/pre-created-users.repository.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/dto/workspace-invitations-pagination.dto.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#312 [PB-2106]: feat/check if workspace invite is valid
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview
