Repository internxt/drive-server-wip, pull requests merged in 2024-12, with the labels that each got.

#438 [_]: feat/switch-from-mailerlite-to-brevo
  .env.template
  package.json
  src/config/configuration.ts
  src/externals/newsletter/index.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#440 [PB-3447] feat: storage changes notifications support for workspaces
  src/externals/notifications/storage.notifications.service.ts
  src/modules/auth/decorators/requester.decorator.spec.ts
  src/modules/auth/decorators/requester.decorator.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/sharing/decorators/behalfUser.decorator.ts
  src/modules/sharing/guards/sharing-permissions.guard.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.controller.ts
  src/modules/user/user.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.module.ts
Labels: enhancement, ready-for-preview

#439 [_]: fix/getFolderByUuid-not-found-when-trashed
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: bug, ready-for-preview

#443 [_]: feat/rollback-from-brevo-to-mailerlite
  .env.template
  package.json
  src/config/configuration.ts
  src/externals/newsletter/index.ts
  yarn.lock
Labels: bug, ready-for-preview

#442 [PB-3189] fix: correctly remove children folders from lookup table on delete
  migrations/20241213035931-fix-update-folder-in-lookup-table-function.js
Labels: bug, ready-for-preview

#441 [PB-3257] Migrate authentication and two-factor endpoints.
  package.json
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/dto/delete-tfa.dto.ts
  src/modules/auth/dto/login-access.dto.ts
  src/modules/auth/dto/login-dto.ts
  src/modules/auth/dto/update-tfa.dto.ts
  src/modules/auth/two-factor-auth.service.spec.ts
  src/modules/auth/two-factor-auth.service.ts
  src/modules/keyserver/key-server.repository.ts
  src/modules/keyserver/key-server.usecase.spec.ts
  src/modules/keyserver/key-server.usecase.ts
  src/modules/user/user.attributes.ts
  src/modules/user/user.domain.ts
  src/modules/user/user.model.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#444 [PB-3334] Feat/access logs
  migrations/20241113173746-create-workspace-logs-table.js
  src/modules/auth/auth.controller.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/trash/trash.controller.ts
  src/modules/user/user.controller.ts
  src/modules/workspaces/attributes/workspace-logs.attributes.ts
  src/modules/workspaces/decorators/workspace-log-action.decorator.ts
  src/modules/workspaces/domains/workspace-log.domain.ts
  src/modules/workspaces/dto/get-workspace-logs.ts
  src/modules/workspaces/interceptors/workspaces-logs.interceptor.spec.ts
  src/modules/workspaces/interceptors/workspaces-logs.interceptor.ts
  src/modules/workspaces/models/workspace-logs.model.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.module.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: ready-for-preview

#446 [_] fix: users without keys are able to log in
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
  src/modules/keyserver/key-server.usecase.spec.ts
  src/modules/keyserver/key-server.usecase.ts
  src/modules/user/user.usecase.ts
Labels: bug, ready-for-preview

#447 [_] chore: added extended http filter exception to auth controller
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
Labels: enhancement, ready-for-preview
