Repository internxt/drive-server-wip, pull requests merged in 2024-06, with the labels that each got.

#323 [_] feat: added extended base http exception
  src/common/http-exception-filter-extended.exception.spec.ts
  src/common/http-exception-filter-extended.exception.ts
  src/modules/workspaces/workspaces.controller.ts
Labels: enhancement, ready-for-preview

#303 [PB-1839] feat/Users can remove themselves from a workspace
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/workspaces/repositories/team.repository.spec.ts
  src/modules/workspaces/repositories/team.repository.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview, workspaces

#306 [PB-1558] Search and filter user list in workspace members
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview, workspaces

#328 [_] chore: enabled folder and files creation with uuid
  src/modules/file/dto/update-file-meta.dto.ts
  src/modules/file/file.controller.ts
  src/modules/folder/dto/create-folder.dto.ts
  src/modules/folder/dto/update-folder-meta.dto.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.usecase.ts
Labels: enhancement, ready-for-preview

#330 [_] chore: use substring operator instead of literals
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
Labels: ready-for-preview, workspaces

#331 [_] chore: added-deleted-files-and-folders-missing-migrations
  migrations/20240612153998-add-deleted-files-table.js
  migrations/20240612154000-add-deleted-folders-table.js
Labels: ready-for-preview

#332 [_]: feat/add-creationTime-files-column
  migrations/20240614091229-add-creationTime-to-files-table.js
  src/modules/file/dto/file.dto.ts
  src/modules/file/file.domain.ts
  src/modules/file/file.model.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/share/share.usecase.spec.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#335 [PB-2248] feat: get folder contents with uuid
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.domain.spec.ts
  src/modules/folder/folder.domain.ts
Labels: enhancement, ready-for-preview

#336 [_] chore: added public user to seeders for environments
  seeders/20240227151200-public-sharings-user.js
Labels: ready-for-preview

#337 [_]: fix/ createFile fix and rootFolderId as uuid when client is drive-web
  src/modules/file/file.usecase.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview, workspaces

#329 [PB-2119, PB-2115] Feat: managing the Workspace Gateway
  src/modules/gateway/dto/delete-workspace.dto.ts
  src/modules/gateway/dto/update-workspace-storage.dto.ts
  src/modules/gateway/gateway.controller.spec.ts
  src/modules/gateway/gateway.controller.ts
  src/modules/gateway/gateway.module.ts
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/gateway/gateway.usecase.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: ready-for-preview, workspaces

#340 feat: added workspace usage and change member assigned space endpoints
  src/modules/workspaces/dto/change-user-assigned-space.dto.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: ready-for-preview, workspaces

#339 [BR-191]: fix: folder size now is being calculated correctly
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/sharing/sharing.service.ts
Labels: bug, ready-for-preview

#327 feat: calculate member usage in workspace
  migrations/20240610121257-add-last-size-sync-column.js
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/workspaces/attributes/workspace-users.attributes.ts
  src/modules/workspaces/domains/workspace-user.domain.ts
  src/modules/workspaces/models/workspace-users.model.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview, workspaces

#317 [PB-2144] feat: share files and folders with other members in the workspace
  migrations/20240520034047-remove-sharing-shared-with-constraint.js
  migrations/20240520041258-add-shared-with-type-to-sharings.js
  src/modules/file/file.usecase.ts
  src/modules/sharing/decorators/behalfUser.decorator.ts
  src/modules/sharing/guards/sharing-permissions.decorator.ts
  src/modules/sharing/guards/sharing-permissions.guard.spec.ts
  src/modules/sharing/guards/sharing-permissions.guard.ts
  src/modules/sharing/models/index.ts
  src/modules/sharing/sharing.controller.spec.ts
  src/modules/sharing/sharing.domain.ts
  src/modules/sharing/sharing.module.ts
  src/modules/sharing/sharing.repository.spec.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/dto/get-items-inside-shared-folder.dto.ts
  src/modules/workspaces/dto/share-item-with-team.dto.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.module.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: ready-for-preview, workspaces
