Repository internxt/drive-server-wip, pull requests merged in 2025-05, with the labels that each got.

#536 [PB-4335] fix(files): files are now not duplicated when listing
  src/modules/file/file.repository.ts
Labels: ready-for-preview

#537 [PB-4335] fix(folders): stop listing duplicated folders
  src/modules/folder/folder.repository.ts
Labels: bug

#538 [_] fix(gateway): cache from drive-server is expired correctly
  src/modules/cache-manager/cache-manager.service.spec.ts
  src/modules/cache-manager/cache-manager.service.ts
Labels: bug, ready-for-preview

#540 [_] feat(backups): get backup folder by id
  src/modules/backups/backup.controller.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
Labels: ready-for-preview

#541 fix(backups): update_at is updated
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: bug, ready-for-preview

#531 fix(pre-created-users): increase encryption key size
  migrations/20250425153614-increase-encryption-key-size.js
  migrations/20250425153626-increase-sharing-invitation-encryption-key-size.js
Labels: bug, preview, ready-for-preview

#545 feat(thumbnails): added uuid support to thumbnails
  src/modules/thumbnail/dto/create-thumbnail.dto.ts
  src/modules/thumbnail/thumbnail.usecase.ts
Labels: ready-for-preview

#544 [_] chore: add status to folder responses
  src/modules/file/file.controller.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
Labels: ready-for-preview

#546 [_] feat(pre-created): return pre public kyber key
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#547 chore(deps): upgraded nestjs and axios for security alerts
  package.json
  yarn.lock
Labels: dependencies, ready-for-preview

#548 [_] fix(folders-deletion): workspaces root folders are now deleted correctly.
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: bug, ready-for-preview

#542 [PB-4371] feat(files): populate file records with missing folder_uuid
  migrations/20250508230425-populate-folder-uuid-files-table.js
Labels: enhancement, ready-for-preview

#549 [PB-4369]: fix/include backup usage in usage response
  src/modules/backups/backup.repository.spec.ts
  src/modules/backups/backup.repository.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
  src/modules/user/dto/responses/get-user-usage.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#550 [_] chore/remove-custom-in-controllers-and-set-compact-to-logger
  src/main.ts
  src/modules/folder/folder.controller.ts
Labels: ready-for-preview

#552 [_]: debug/add debug logs
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/gateway/gateway.usecase.ts
Labels: ready-for-preview

#554 chore: enhance cache logging with debug information
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#558 chore(deps): pg version upgraded and mariadb removed
  package.json
  yarn.lock
Labels: dependencies, ready-for-preview

#532 feat(recover-account): recover account with legacy backup file
  src/externals/crypto/crypto.service.ts
  src/lib/jwt.ts
  src/modules/user/dto/legacy-recover-account.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
Labels: enhancement, ready-for-preview

#568 [_] Add backs -> "feat(recover-account): recover account with legacy backup"
  src/externals/crypto/crypto.service.ts
  src/lib/jwt.ts
  src/modules/user/dto/legacy-recover-account.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
Labels: ready-for-preview

#569 [_] fix(analytics): prevent rudderstack from crashing the app
  src/externals/notifications/listeners/analytics.listener.ts
  src/externals/notifications/listeners/auth.listener.ts
  src/lib/analytics.ts
Labels: bug, ready-for-preview

#565 [PB-4418]: chore/code smells readonly
  src/externals/apn/apn.service.ts
  src/externals/avatar/avatar.service.ts
  src/externals/bridge/bridge.service.ts
  src/externals/crypto/crypto.service.ts
  src/externals/http/http.service.ts
  src/externals/mailer/mailer.service.ts
  src/externals/notifications/events/event.ts
  src/externals/notifications/listeners/notification.listener.ts
  src/externals/notifications/listeners/send-link.listener.ts
  src/externals/notifications/listeners/share-link.listener.ts
  src/externals/notifications/notification.service.ts
  src/externals/notifications/storage.notifications.service.ts
  src/externals/payments/payments.service.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/jwt.strategy.ts
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/feature-limit/feature-limit-migration.service.ts
  src/modules/feature-limit/feature-limit.repository.ts
  src/modules/feature-limit/feature-limit.usecase.ts
  src/modules/file/file.repository.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/fuzzy-search/fuzzy-search.usecase.ts
  src/modules/fuzzy-search/look-up.repository.ts
  src/modules/keyserver/key-server.repository.ts
  src/modules/keyserver/key-server.usecase.ts
  src/modules/security/mail-limit/mail-limit.repository.ts
  src/modules/send/send-link.repository.ts
  src/modules/send/send.controller.ts
  src/modules/send/send.usecase.ts
  src/modules/share/share.controller.ts
  src/modules/share/share.repository.ts
  src/modules/share/share.usecase.ts
  src/modules/sharing/guards/sharing-permissions.guard.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/thumbnail/thumbnail.repository.ts
  src/modules/thumbnail/thumbnail.usecase.ts
  src/modules/trash/trash.controller.ts
  src/modules/trash/trash.usecase.ts
  src/modules/user/pre-created-users.repository.ts
  src/modules/user/referrals.repository.ts
  src/modules/user/user-referrals.repository.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
  src/modules/workspaces/guards/workspaces.guard.ts
  src/modules/workspaces/repositories/team.repository.ts
  src/shared-workspace/shared-workspace.repository.ts
Labels: ready-for-preview

#556 [_]: fix/optimistic cache updates
  src/modules/cache-manager/cache-manager.service.spec.ts
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/gateway/gateway.usecase.ts
  src/modules/user/user.usecase.ts
Labels: bug, ready-for-preview
