Repository internxt/drive-server-wip, pull requests merged in 2025-01, with the labels that each got.

#448 [PB-3595] feat: migrated credentials and email verification endpoints
  .env.template
  src/config/configuration.ts
  src/externals/mailer/mailer.service.ts
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/are-credentials-correct.dto.ts
  src/modules/security/mail-limit/mail-limit.domain.ts
  src/modules/user/dto/verify-email.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#263 [PB-267]: chore/refactor passwordChangedAt middleware variable naming and remove function
  src/lib/jwt.ts
  src/modules/auth/jwt.strategy.ts
Labels: auth-module-change, ready-for-preview

#449 [_] chore: modified verification endpoints to a more restful name
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
Labels: ready-for-preview

#452 [_] fix: lower case emails on auth endpoints
  src/modules/auth/auth.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#455 [PB-3601] feat: migrate user endpoints
  src/modules/user/dto/update-profile.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#450 [_]: feat/accept-multiple-keys-update-on-change-password
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/decorators/client.decorator.ts
  src/modules/auth/dto/login-access.dto.ts
  src/modules/keyserver/dto/keys.dto.ts
  src/modules/keyserver/key-server.domain.spec.ts
  src/modules/keyserver/key-server.domain.ts
  src/modules/keyserver/key-server.model.ts
  src/modules/keyserver/key-server.repository.ts
  src/modules/keyserver/key-server.usecase.spec.ts
  src/modules/keyserver/key-server.usecase.ts
  src/modules/user/dto/create-user.dto.ts
  src/modules/user/dto/recover-account.dto.ts
  src/modules/user/dto/update-password.dto.ts
  src/modules/user/pre-created-user.domain.ts
  src/modules/user/pre-created-users.model.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#460 [_] chore: upgraded ts-jest library and fixed unit test
  package.json
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.spec.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  yarn.lock
Labels: bug, ready-for-preview

#462 [PB-3625] chore: increase public and private keys size migration
  migrations/20250128040758-increase-keyserver-public-and-private-keys-length.js
Labels: enhancement, ready-for-preview

#463 [_] fix: sequelize added to keys migration
  migrations/20250128040758-increase-keyserver-public-and-private-keys-length.js
Labels: bug

#461 [PB-3625] feat: add kyber keys support to update password
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/decorators/client.decorator.ts
  src/modules/keyserver/key-server.domain.spec.ts
  src/modules/keyserver/key-server.domain.ts
  src/modules/keyserver/key-server.model.ts
  src/modules/keyserver/key-server.repository.ts
  src/modules/keyserver/key-server.usecase.spec.ts
  src/modules/keyserver/key-server.usecase.ts
  src/modules/user/dto/update-password.dto.ts
  src/modules/user/pre-created-user.domain.ts
  src/modules/user/pre-created-users.model.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: ready-for-preview

#464 [PB-3625] feat: added support for kyber keys on log in and user creation
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/login-access.dto.ts
  src/modules/keyserver/dto/keys.dto.ts
  src/modules/keyserver/key-server.usecase.spec.ts
  src/modules/keyserver/key-server.usecase.ts
  src/modules/user/dto/create-user.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#445 [PB-2424] User can't details of an item shared by another member
  migrations/20250128142106-add-view-details-to-permissions.js
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/share/decorators/is-shared-item.decorator.ts
  src/modules/sharing/dto/get-items-and-shared-folders.dto.ts
  src/modules/sharing/guards/sharing-permissions.guard.spec.ts
  src/modules/sharing/guards/sharing-permissions.guard.ts
  src/modules/sharing/guards/sharings-token.interface.ts
  src/modules/sharing/sharing.domain.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/workspaces/dto/get-workspace-logs.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#466 [_] chore: increase sharings encryption key size
  migrations/20250131123014-increase-sharing-encryption-key-size.js
  migrations/20250131124626-increase-sharing-invitation-encryption-key-size.js
Labels: ready-for-preview
