Repository internxt/drive-server-wip, pull requests merged in 2025-06, with the labels that each got.

#562 [PB-4418]: chore/fix codesmells introduced in 2024
  package.json
  src/externals/multer/index.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/trash/trash.controller.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/workspaces/guards/workspaces-resources-in-behalf.decorator.ts
  src/modules/workspaces/guards/workspaces-resources-in-behalf.types.ts
  src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.spec.ts
  src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.ts
  yarn.lock
Labels: ready-for-preview

#573 chore/reintroduce 2025 codesmell fixes
  src/common/enums/platform.enum.ts
  src/common/http-global-exception-filter.exception.ts
  src/externals/bridge/bridge.service.ts
  src/externals/http/http.module.ts
  src/externals/notifications/listeners/analytics.listener.ts
  src/lib/import-esm-package.ts
  src/lib/time.ts
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/decorators/client.decorator.ts
  src/modules/auth/decorators/requester.decorator.ts
  src/modules/auth/decorators/workspace.decorator.ts
  src/modules/auth/gateway-rs256jwt.strategy.ts
  src/modules/feature-limit/feature-limit.usecase.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/file/guards/upload.guard.spec.ts
  src/modules/folder/dto/files-existence-in-folder.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/share/decorators/is-shared-item.decorator.ts
  src/modules/sharing/guards/sharing-permissions.guard.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.controller.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/interceptors/workspaces-logs.interceptor.spec.ts
  src/modules/workspaces/interceptors/workspaces-logs.interceptor.ts
  src/modules/workspaces/workspaces.controller.spec.ts
Labels: ready-for-preview

#575 [PB-4514] feat(token): remove network hash from JWT
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: bug, ready-for-preview

#563 [PB-4418]: chore/fix codesmells introduced in 2023
  src/externals/http/http.service.ts
  src/externals/notifications/listeners/notification.listener.ts
  src/lib/contants.ts
  src/modules/auth/jwt.strategy.ts
  src/modules/auth/rs256jwt.strategy.ts
  src/modules/file/file.domain.ts
  src/modules/folder/dto/folder.dto.ts
  src/modules/folder/folder.domain.ts
  src/modules/fuzzy-search/look-up.repository.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.domain.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
  src/modules/user/user-referrals.repository.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#576 [_] refactor(sharings-errors): leave logging to global exception filter
  src/modules/sharing/sharing.controller.ts
Labels: ready-for-preview

#581 [PB-4417]: chore/enhance unit tests for TrashController and TrashUseCases
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.usecase.spec.ts
Labels: ready-for-preview

#572 [PB-4417]: chore/improve workspace module test coverage
  src/modules/workspaces/guards/workspaces-resources-in-behalf.decorator.spec.ts
  src/modules/workspaces/repositories/team.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
Labels: ready-for-preview

#582 [PB-4417]: chore/file controller and usecase test coverage
  jest.setup.js
  package.json
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
Labels: ready-for-preview

#585 [PB-4416]: chore/file UUID in thumbnails
  src/modules/file/file.model.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/thumbnail/dto/thumbnail.dto.ts
  src/modules/thumbnail/thumbnail.attributes.ts
  src/modules/thumbnail/thumbnail.domain.ts
  src/modules/thumbnail/thumbnail.model.ts
  src/modules/thumbnail/thumbnail.repository.spec.ts
  src/modules/thumbnail/thumbnail.repository.ts
  src/modules/thumbnail/thumbnail.usecase.spec.ts
  src/modules/thumbnail/thumbnail.usecase.ts
Labels: enhancement, ready-for-preview

#588 [_] chore(deps): upgrade platform-express patch version
  package.json
  yarn.lock
Labels: dependencies, ready-for-preview

#590 [_] chore(deps): update new relic
  package.json
  yarn.lock
Labels: ready-for-preview

#592 Send DTOs in websocket notifications
  src/externals/notifications/storage.notifications.service.spec.ts
  src/externals/notifications/storage.notifications.service.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/workspaces/workspaces.controller.ts
Labels: ready-for-preview

#594 [_]: feat(users)/implement get me/upload-status endpoint to determine wether a user has ever uploaded any files
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/user/dto/responses/get-upload-status.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#597 chore(actions): added close stalled PRs action
  .github/workflows/stale-and-close.yml
Labels: ready-for-preview

#596 [_]: feat/move get share domains endpoint
  src/modules/sharing/sharing.controller.spec.ts
  src/modules/sharing/sharing.controller.ts
Labels: enhancement, ready-for-preview

#564 [_]: chore(eslint): update rules to improve code quality
  .eslintrc.js
Labels: stalled, ready-for-preview
