Repository internxt/drive-server-wip, pull requests merged in 2025-02, with the labels that each got.

#467 [_] chore: get root folder on access
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#468 [_] chore: fixed view details migration for local environments
  migrations/20250128142106-add-view-details-to-permissions.js
Labels: bug, ready-for-preview

#469 [_] fix: invited editor users are now able to share inside shared folders
  src/common/extract-data-from-request.ts
  src/modules/sharing/guards/sharing-permissions.guard.ts
Labels: ready-for-preview

#451 [_] feat: added deactivate user endpoints
  src/externals/bridge/bridge.service.spec.ts
  src/externals/bridge/bridge.service.ts
  src/externals/notifications/events/deactivation-request.event.ts
  src/externals/notifications/listeners/analytics.listener.spec.ts
  src/externals/notifications/listeners/analytics.listener.ts
  src/modules/app-sumo/app-sumo.repository.ts
  src/modules/app-sumo/app-sumo.usecase.ts
  src/modules/backups/backup.module.ts
  src/modules/backups/backup.repository.ts
  src/modules/backups/backup.usecase.ts
  src/modules/backups/models/backup.model.ts
  src/modules/backups/models/device.model.ts
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/user/dto/confirm-deactivation.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#470 [PB-3686] chore: added extended exception filter to move files and folders
  src/modules/file/file.controller.ts
  src/modules/folder/folder.controller.ts
Labels: ready-for-preview

#473 [_]: Feat/add login-access logs
  src/modules/auth/auth.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#472 Add file and folder dto
  package.json
  src/modules/file/dto/responses/get-files.dto.ts
  src/modules/file/file.controller.ts
  src/modules/folder/dto/responses/get-folders.dto.ts
  src/modules/folder/folder.controller.ts
  yarn.lock
Labels: ready-for-preview

#474 [PB-3686] fix: folders with trashed parent can now be moved
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: bug, ready-for-preview

#475 [PB-3868] fix: trashed folders metadata can now be updated
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
Labels: bug, ready-for-preview

#477 [_] chore: added workspace owners to auth token
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#476 Add endpoint types
  .gitattributes
  src/modules/file/dto/move-file.dto.ts
  src/modules/file/dto/replace-file.dto.ts
  src/modules/file/dto/responses/file.dto.ts
  src/modules/file/file.controller.ts
  src/modules/folder/dto/create-folder.dto.ts
  src/modules/folder/dto/move-folder.dto.ts
  src/modules/folder/dto/responses/folder.dto.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.usecase.ts
  src/modules/trash/dto/controllers/move-items-to-trash.dto.ts
  src/modules/workspaces/dto/create-workspace-folder.dto.ts
  src/modules/workspaces/dto/reponse/workspace-credentials.dto.ts
  src/modules/workspaces/dto/reponse/workspace.dto.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: ready-for-preview
