Repository internxt/drive-server-wip, pull requests merged in 2025-09, with the labels that each got.

#685 [_] feat(notifications): add notifications database tables migrations
  migrations/20250828150710-create-notifications-table.js
  migrations/20250828150711-create-user-notification-status-table.js
Labels: enhancement, ready-for-preview

#691 [_]: fix/user-response-properties
  src/modules/user/user.controller.ts
Labels: ready-for-preview

#690 feat(notifications): added create endpoint
  src/modules/notifications/domain/notification.domain.ts
  src/modules/notifications/dto/create-notification.dto.ts
  src/modules/notifications/dto/notification-response.dto.ts
  src/modules/notifications/notifications.controller.spec.ts
  src/modules/notifications/notifications.controller.ts
  src/modules/notifications/notifications.guard.spec.ts
  src/modules/notifications/notifications.guard.ts
  src/modules/notifications/notifications.module.ts
  src/modules/notifications/notifications.repository.spec.ts
  src/modules/notifications/notifications.repository.ts
  src/modules/notifications/notifications.usecase.spec.ts
  src/modules/notifications/notifications.usecase.ts
Labels: enhancement, ready-for-preview

#697 [_] feat(notifications): add gateway guard to notifications
  src/modules/notifications/notifications.controller.ts
Labels: enhancement, ready-for-preview

#698 [PB-4899]: feat/add-rename-operation-to-move-files-endpoint
  src/modules/file/dto/move-file.dto.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
Labels: enhancement, ready-for-preview

#699 [_] feat(move-folder): allow renaming when moving folder
  src/modules/folder/dto/move-folder.dto.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#700 [PB-4740] Feat/use pino logger
  package.json
  src/app.module.ts
  src/common/http-global-exception-filter.exception.spec.ts
  src/common/http-global-exception-filter.exception.ts
  src/externals/notifications/listeners/notification.listener.ts
  src/main.ts
  src/middlewares/requests-logger.interceptor.ts
  src/middlewares/requests-logger.ts
  yarn.lock
Labels: ready-for-preview, refactor

#706 [PB-4731]: implement caching for user avatars in cache manager
  src/modules/cache-manager/cache-manager.service.spec.ts
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#707 [PB-2394] chore: create extended statistics for user_id, updated_at
  migrations/20250916110659-create-files-user-updated-statistics.js
Labels: ready-for-preview

#708 [PB-4942] feat(tiers): add new tiers seed
  migrations/20250916144443-add-name-column-to-limits-table.js
  migrations/20250916145418-seed-new-pricing-tiers.js
Labels: enhancement, ready-for-preview

#712 [_] chore: remove template ids from .env template
  .env.template
  .env.test
Labels: ready-for-preview

#714 [PB-4942] feat/seed-lifetime-tiers
  migrations/20250919134806-seed-lifetime-tiers.js
Labels: ready-for-preview

#722 [_] fix/remove-duplicate-free-tier-from-database
  migrations/20250925185947-reassign-free-tier-label.js
Labels: ready-for-preview
