Repository internxt/drive-server-wip, pull requests merged in 2025-07, with the labels that each got.

#602 [PB-4409]: chore/update Node.js version to 22.17.0
  Dockerfile
  development.Dockerfile
  infrastructure/development.Dockerfile
  infrastructure/preview.Dockerfile
  jest.setup.js
Labels: enhancement, ready-for-preview

#586 [_]: refactor/remove old Share module and related components
  src/externals/notifications/events/share-link-created.event.ts
  src/externals/notifications/events/share-link-view.event.ts
  src/externals/notifications/listeners/analytics.listener.ts
  src/externals/notifications/listeners/share-link.listener.ts
  src/externals/notifications/notifications.module.ts
  src/modules/backups/backup.module.ts
  src/modules/file/dto/file.dto.ts
  src/modules/file/file.domain.ts
  src/modules/file/file.model.ts
  src/modules/file/file.module.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.ts
  src/modules/share/dto/create-share.dto.ts
  src/modules/share/dto/get-down-files.dto.ts
  src/modules/share/dto/share.dto.ts
  src/modules/share/dto/update-share.dto.ts
  src/modules/share/share.controller.ts
  src/modules/share/share.domain.ts
  src/modules/share/share.module.ts
  src/modules/share/share.repository.ts
  src/modules/share/share.usecase.spec.ts
  src/modules/share/share.usecase.ts
  src/modules/sharing/decorators/is-shared-item.decorator.ts
  src/modules/thumbnail/thumbnail.module.ts
  src/modules/trash/trash.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/workspaces.controller.ts
Labels: ready-for-preview

#609 fix: use https and http agentkeepalive as expected, added extra log t…
  src/externals/http/http.module.ts
  src/externals/notifications/listeners/notification.listener.ts
Labels: bug, ready-for-preview

#610 [_] Fix/use agentkeepalive
  src/externals/http/http.module.ts
  src/externals/notifications/listeners/notification.listener.ts
Labels: ready-for-preview

#611 [_] Refactor/use try catch on event and singleton agent
  src/externals/http/http.module.ts
  src/externals/notifications/listeners/notification.listener.ts
Labels: ready-for-preview

#607 [_]: feat(migrations)/add not-null constraint on file_uuid in thumbnails table
  migrations/20250707135035-add-not-null-constraint-on-thumbnail.js
Labels: enhancement, ready-for-preview

#612 [PB-4417]: chore/improve sharings repository test coverage
  src/modules/sharing/sharing.repository.spec.ts
  test/fixtures.spec.ts
  test/fixtures.ts
Labels: ready-for-preview

#613 [_] chore: increase sockets timeout to 16 secs
  src/externals/http/http.module.ts
Labels: ready-for-preview

#614 [_] refactor: stop using some deprecated functions and solved code smells
  src/externals/bridge/bridge.service.spec.ts
  src/modules/feature-limit/feature-limits.guard.spec.ts
  src/modules/file/file.controller.spec.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/workspaces/guards/workspaces.guard.spec.ts
Labels: ready-for-preview

#616 [PB-4582] feat: add create device, link device to folder and get devices v2
  src/modules/backups/backup.controller.spec.ts
  src/modules/backups/backup.controller.ts
  src/modules/backups/backup.repository.spec.ts
  src/modules/backups/backup.repository.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
  src/modules/backups/device.domain.ts
  src/modules/backups/dto/create-device-and-attach-folder.dto.ts
  src/modules/backups/dto/create-device-and-folder.dto.ts
  src/modules/backups/dto/get-devices-and-folders.dto.ts
  src/modules/backups/dto/responses/device-as-folder.dto.ts
  src/modules/backups/dto/responses/device.dto.ts
  src/modules/backups/models/device.attributes.ts
  src/modules/backups/models/device.model.ts
  src/modules/folder/folder.usecase.ts
  src/modules/user/user.domain.ts
  test/fixtures.ts
Labels: ready-for-preview

#617 [_] chore: reduce axios timeout to default value
  src/externals/http/http.module.ts
Labels: ready-for-preview

#619 [PB-4417]: chore/sharing controller test coverage
  src/modules/sharing/sharing.controller.spec.ts
Labels: ready-for-preview

#620 [PB-4417]: chore/sharings service test coverage
  src/modules/sharing/sharing.repository.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
  test/fixtures.ts
Labels: ready-for-preview

#598 [_]: feat/completely clear workspace on reset
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#506 [PB-3702]: feat/recover keys on account recovery
  src/modules/file/file.module.ts
  src/modules/user/dto/recover-account.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: auth-module-change, enhancement, preview, ready-for-preview, blocked

#622 [_] feat: add logs to user destructive operations
  src/lib/http/http-exception.filter.ts
  src/modules/backups/backup.controller.ts
  src/modules/folder/folder.controller.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/trash/trash.controller.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#580 [PB-4417]: chore/user module test coverage
  src/modules/user/attempt-change-email.repository.spec.ts
  src/modules/user/user.repository.spec.ts
  src/modules/user/user.usecase.spec.ts
Labels: stalled, ready-for-preview

#623 [_] fix(unit-tests): fixed some unit tests broken due to conflict
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#600 [PB-4416]: refactor/replace-fileid-usage-with-uuid-in-trash-and-file-modules
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/trash/dto/controllers/delete-item.dto.ts
  src/modules/trash/dto/controllers/move-items-to-trash.dto.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.controller.ts
  src/modules/trash/trash.usecase.spec.ts
Labels: enhancement, ready-for-preview

#624 [_] refactor: improve swagger doc for move and delete item from trash
  src/externals/notifications/storage.notifications.service.spec.ts
  src/externals/notifications/storage.notifications.service.ts
  src/modules/trash/dto/controllers/delete-item.dto.ts
  src/modules/trash/dto/controllers/delete-items.dto.spec.ts
  src/modules/trash/dto/controllers/move-items-to-trash.dto.spec.ts
  src/modules/trash/dto/controllers/move-items-to-trash.dto.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.controller.ts
  src/modules/workspaces/interceptors/workspaces-logs.interceptor.ts
Labels: ready-for-preview

#625 [_]: fix/remove conditional Catcha guard
  src/externals/captcha/captcha.service.ts
  src/modules/auth/auth.controller.ts
Labels: bug, ready-for-preview

#627 [_]: fix/update JWT secret retrieval and add debug logging
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#628 [_] feat: add folder to device migrate response
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
Labels: enhancement, ready-for-preview

#629 fix: fixed devices v2 dto
  src/modules/backups/backup.usecase.ts
  src/modules/backups/dto/create-device-and-attach-folder.dto.ts
  src/modules/backups/dto/create-device-and-folder.dto.ts
  src/modules/backups/dto/get-devices-and-folders.dto.ts
Labels: ready-for-preview

#634 [_]: feature/refresh avatar user
  src/modules/user/dto/responses/refresh-avatar.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
Labels: enhancement, ready-for-preview

#636 [_] fix: devices v2 use key instead of id
  src/modules/backups/backup.controller.ts
  src/modules/backups/backup.repository.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
Labels: bug

#639 [PB-4693] feat: add updated at index for removed folders
  migrations/20250730231958-create-updated-at-folders-index.js
Labels: enhancement, ready-for-preview

#642 [_]: feat/add-missing-newToken-property
  src/modules/user/user.controller.ts
Labels: enhancement, ready-for-preview
