Repository internxt/drive-server-wip, pull requests merged in 2025-03, with the labels that each got.

#479 [_]: feat/block-uploads-on-affected-versions
  package.json
  src/modules/file/file.controller.ts
  src/modules/file/guards/upload.guard.spec.ts
  src/modules/file/guards/upload.guard.ts
  yarn.lock
Labels: ready-for-preview

#480 [_] feat: added check user storage stackability endpoint to gateway
  src/lib/convert-size-to-bytes.spec.ts
  src/lib/convert-size-to-bytes.ts
  src/modules/gateway/dto/check-storage-expansion.dto.ts
  src/modules/gateway/gateway.controller.spec.ts
  src/modules/gateway/gateway.controller.ts
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/gateway/gateway.usecase.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#482 [PB-4033] feat: rollback users on signup error
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/trash/trash.usecase.spec.ts
  src/modules/trash/trash.usecase.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#483 [_]: Add swagger documentation to login and get folders endpoint
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/login-access.dto.ts
  src/modules/auth/dto/responses/login-access-response.dto.ts
  src/modules/auth/dto/responses/login-response.dto.ts
  src/modules/auth/dto/responses/user.dto.ts
  src/modules/folder/dto/responses/get-folder-content.dto.ts
  src/modules/folder/folder.controller.ts
  src/modules/workspaces/dto/reponse/workspace.dto.ts
Labels: ready-for-preview

#481 [PB-4051] feat: migrated usage endpoint and implement cache module
  package.json
  src/config/configuration.ts
  src/modules/cache-manager/cache-manager.module.spec.ts
  src/modules/cache-manager/cache-manager.module.ts
  src/modules/cache-manager/cache-manager.service.spec.ts
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/user/dto/responses/get-user-usage.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#486 [PB-4104] feat: Migrate limit and backup device endpoints
  src/externals/crypto/crypto.service.ts
  src/modules/backups/backup.controller.spec.ts
  src/modules/backups/backup.controller.ts
  src/modules/backups/backup.domain.ts
  src/modules/backups/backup.module.ts
  src/modules/backups/backup.repository.spec.ts
  src/modules/backups/backup.repository.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
  src/modules/backups/device.domain.ts
  src/modules/backups/dto/create-backup.dto.ts
  src/modules/backups/dto/create-device-as-folder.dto.ts
  src/modules/backups/dto/create-device.dto.ts
  src/modules/backups/models/backup.attributes.ts
  src/modules/backups/models/backup.model.ts
  src/modules/backups/models/device.attributes.ts
  src/modules/backups/models/device.model.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#488 [PB-4108] Feat: migrate thumbnail endpoint
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/thumbnail/dto/create-thumbnail.dto.ts
  src/modules/thumbnail/dto/thumbnail.dto.ts
  src/modules/thumbnail/thumbnail.model.ts
  src/modules/thumbnail/thumbnail.module.ts
  src/modules/thumbnail/thumbnail.repository.spec.ts
  src/modules/thumbnail/thumbnail.repository.ts
  src/modules/thumbnail/thumbnail.usecase.spec.ts
  src/modules/thumbnail/thumbnail.usecase.ts
Labels: ready-for-preview

#484 [PB-3705] feat: migrate storage endpoints
  src/externals/notifications/storage.notifications.service.ts
  src/modules/backups/backup.controller.ts
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  src/modules/thumbnail/thumbnail.usecase.spec.ts
  src/modules/thumbnail/thumbnail.usecase.ts
  src/modules/trash/trash.usecase.spec.ts
Labels: ready-for-preview

#489 [PB-4112]: feat/add workspace joined and left notification events
  src/externals/notifications/storage.notifications.service.spec.ts
  src/externals/notifications/storage.notifications.service.ts
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/gateway/gateway.usecase.ts
  src/modules/workspaces/workspaces.controller.spec.ts
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#490 [PB-4106] Feat: migrate backup and device endpoints
  src/modules/backups/backup.controller.spec.ts
  src/modules/backups/backup.controller.ts
  src/modules/backups/backup.repository.spec.ts
  src/modules/backups/backup.repository.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
Labels: ready-for-preview

#492 [_] feat: added asymmetric encryption service
  package.json
  src/externals/asymmetric-encryption/asymmetric-encryption.module.ts
  src/externals/asymmetric-encryption/asymmetric-encryption.service.spec.ts
  src/externals/asymmetric-encryption/asymmetric-encryption.service.ts
  src/externals/asymmetric-encryption/openpgp.spec.ts
  src/externals/asymmetric-encryption/openpgp.ts
  src/externals/asymmetric-encryption/providers/kyber.provider.ts
  src/externals/asymmetric-encryption/utils.spec.ts
  src/externals/asymmetric-encryption/utils.ts
  src/lib/import-esm-package.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#495 [_] feat: add doc to get workspace files
  src/modules/folder/folder.controller.ts
  src/modules/workspaces/dto/get-workspace-files.dto.ts
Labels: ready-for-preview

#493 [_] Feat: add kyber support for pre created users
  package.json
  src/modules/sharing/sharing.domain.ts
  src/modules/user/pre-created-user.domain.ts
  src/modules/user/pre-created-users.attributes.ts
  src/modules/user/pre-created-users.model.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#496 [_] fix: pre created users assign revocation certificate
  src/externals/asymmetric-encryption/asymmetric-encryption.service.ts
  src/modules/user/user.controller.ts
Labels: bug, ready-for-preview

#499 [PB-4129] feat(logger): added global exception filter
  src/app.module.ts
  src/common/http-global-exception-filter.exception.spec.ts
  src/common/http-global-exception-filter.exception.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/decorators/client.decorator.ts
  src/modules/file/file.controller.ts
  src/modules/folder/folder.controller.ts
  src/modules/gateway/gateway.controller.ts
  src/modules/user/user.controller.ts
  src/modules/workspaces/workspaces.controller.ts
Labels: enhancement, ready-for-preview

#500 [PB-4129] feat(logger): use subcategories inside UNEXPECTED_ERRROR
  src/common/http-global-exception-filter.exception.spec.ts
  src/common/http-global-exception-filter.exception.ts
Labels: enhancement, ready-for-preview

#501 [PB-4133] chore(deps): update nestjs to 10.4.15
  package.json
  yarn.lock
Labels: dependencies, ready-for-preview

#503 chore(logs): add user id to global error logger
  src/common/http-global-exception-filter.exception.ts
Labels: ready-for-preview

#504 [_]: fix/include member data when sending user removed notifications
  src/modules/workspaces/workspaces.controller.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: bug, ready-for-preview

#502 [_]: chore/implement deleteFileByFileId functionality
  src/modules/file/file.controller.spec.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
Labels: ready-for-preview
