Repository internxt/drive-server-wip, pull requests merged in 2025-04, with the labels that each got.

#508 [PB-4133] chore(deps): reapply update dependencies to latest minor versions
  package.json
  src/app.module.ts
  src/lib/winston-logger.ts
  yarn.lock
Labels: dependencies, ready-for-preview

#510 fix(deps): rollback type/jsonwebtoken version to 9.0.2
  package.json
  yarn.lock
Labels: bug, dependencies, ready-for-preview

#511 [_] fix(validations): check public sharing existence and remove file constructor name validation
  src/common/pipes/validate-uuid.pipe.spec.ts
  src/common/pipes/validate-uuid.pipe.ts
  src/modules/backups/backup.controller.ts
  src/modules/file/file.controller.ts
  src/modules/file/file.domain.ts
  src/modules/folder/folder.controller.ts
  src/modules/gateway/gateway.controller.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.service.ts
  src/modules/workspaces/workspaces.controller.ts
Labels: bug, ready-for-preview

#512 [_] chore(logs): disable logs colors if not on dev
  src/main.ts
Labels: enhancement, ready-for-preview

#498 [_] feat: create backup devices dto
  src/modules/backups/backup.controller.ts
  src/modules/backups/backup.usecase.spec.ts
  src/modules/backups/backup.usecase.ts
  src/modules/backups/dto/create-device-as-folder.dto.ts
  src/modules/backups/dto/responses/device.dto.ts
  src/modules/user/dto/responses/get-user-limit.dto.ts
  src/modules/user/user.controller.ts
Labels: ready-for-preview

#513 [_] chore(dto): creation of Refresh Token DTO, Query Updates, and Status Addition in Folder Metadata
  src/modules/user/dto/responses/refresh-token.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#514 [_] refactor: userController error handling and unit tests logger
  src/common/http-global-exception-filter.exception.spec.ts
  src/externals/notifications/storage.notifications.service.spec.ts
  src/modules/app-sumo/app-sumo.usecase.ts
  src/modules/auth/auth.controller.spec.ts
  src/modules/gateway/gateway.controller.spec.ts
  src/modules/gateway/gateway.usecase.spec.ts
  src/modules/keyserver/key-server.usecase.spec.ts
  src/modules/trash/trash.controller.spec.ts
  src/modules/trash/trash.usecase.spec.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
Labels: ready-for-preview

#515 [_] feat(limit): added cache to get user limit
  src/externals/http/http.module.ts
  src/modules/cache-manager/cache-manager.service.spec.ts
  src/modules/cache-manager/cache-manager.service.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#516 feat(PQ): added PQ encryption to replace pre created user function
  src/modules/sharing/sharing.domain.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/user/pre-created-user.domain.ts
  src/modules/user/pre-created-users.attributes.ts
  src/modules/user/pre-created-users.model.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  test/fixtures.ts
Labels: enhancement, ready-for-preview

#519 [_] chore: changed docker node image
  Dockerfile
  development.Dockerfile
  infrastructure/development.Dockerfile
  infrastructure/preview.Dockerfile
Labels: ready-for-preview

#517 [_] feat(sharings): add item sharing info endpoint
  src/modules/sharing/dto/response/get-item-sharing-info.dto.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.repository.ts
  src/modules/sharing/sharing.service.spec.ts
  src/modules/sharing/sharing.service.ts
Labels: ready-for-preview

#520 feat(recover-account): add reset workspace functions
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/workspaces/repositories/workspaces.repository.spec.ts
  src/modules/workspaces/repositories/workspaces.repository.ts
  src/modules/workspaces/workspaces.usecase.spec.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: ready-for-preview

#521 [PB-4092]: fix/find-files-with-empty-type
  src/externals/asymmetric-encryption/asymmetric-encryption.service.spec.ts
  src/lib/path.spec.ts
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/user/user.usecase.spec.ts
Labels: bug, ready-for-preview

#525 [_] fix(tests): fixed tests failing randomly due to kyber provider
  src/lib/import-esm-package.ts
Labels: ready-for-preview

#524 [PB-3702] feat(reset-account): empty workspace and sharings when user resets their account
  src/modules/folder/folder.module.ts
  src/modules/user/user.module.ts
  src/modules/user/user.usecase.spec.ts
  src/modules/user/user.usecase.ts
  src/modules/workspaces/workspaces.usecase.ts
Labels: enhancement, ready-for-preview

#527 feat(pre-created-users): generate hidden kyber keys
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#528 feat(pre-created-users): pass new generated kyber key replacePreCreatedUser
  src/modules/user/user.controller.ts
Labels: ready-for-preview

#529 [_] feat(refresh-token): added user to refresh token endpoint
  src/modules/user/dto/responses/refresh-token.dto.ts
  src/modules/user/user.controller.spec.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
Labels: enhancement, ready-for-preview

#533 [_] chore(public-sharings): handle requests to bridge concurrently
  src/modules/sharing/sharing.service.ts
Labels: ready-for-preview
