Repository internxt/drive-server-wip, pull requests merged in 2025-08, with the labels that each got.

#643 [_] fix: add modification date to replace file endpoint
  src/modules/file/dto/replace-file.dto.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
Labels: bug, ready-for-preview

#647 [_] fix: lowercase email
  src/modules/user/user.controller.ts
  src/modules/user/user.usecase.ts
Labels: ready-for-preview

#638 [PB-4693] Feat/add deleted items cleanup cronjob
  package.json
  src/app.module.ts
  src/config/configuration.ts
  src/modules/file/file.repository.ts
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/jobs/constants.ts
  src/modules/jobs/jobs.module.ts
  src/modules/jobs/models/job-execution.model.ts
  src/modules/jobs/repositories/job-execution.repository.ts
  src/modules/jobs/services/redis.service.spec.ts
  src/modules/jobs/services/redis.service.ts
  src/modules/jobs/tasks/deleted-items-cleanup.task.spec.ts
  src/modules/jobs/tasks/deleted-items-cleanup.task.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#648 [_] chore: add pr size limit action
  .github/workflows/check-pr-size.yml
Labels: ready-for-preview

#651 [_] feat: added more logs to deleted items cleanup job
  src/modules/jobs/tasks/deleted-items-cleanup.task.spec.ts
  src/modules/jobs/tasks/deleted-items-cleanup.task.ts
Labels: ready-for-preview

#653 [_] fix: instance does not crash anymore if redis is not available
  src/modules/jobs/services/redis.service.spec.ts
  src/modules/jobs/services/redis.service.ts
Labels: ready-for-preview

#654 [_] fix: empty trash timeout fixed when there are too many items
  src/modules/file/file.repository.spec.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.repository.spec.ts
  src/modules/folder/folder.repository.ts
  src/modules/folder/folder.usecase.ts
  src/modules/trash/trash.usecase.spec.ts
  src/modules/trash/trash.usecase.ts
Labels: ready-for-preview, refactor

#656 [_] fix: added owner info to get files in shared folder endpoint
  src/modules/sharing/dto/response/get-folders-in-shared-folder.dto.ts
  src/modules/sharing/dto/response/shared-base.dto.ts
  src/modules/sharing/dto/response/shared-file-item.dto.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.service.ts
Labels: ready-for-preview

#657 [_] chore(sharings): added DTO for get content in sharing folders
  src/modules/sharing/dto/get-items-in-shared-folder.dto.ts
  src/modules/sharing/dto/response/get-folders-in-shared-folder.dto.ts
  src/modules/sharing/dto/response/shared-base.dto.ts
  src/modules/sharing/dto/response/shared-file-item.dto.ts
  src/modules/sharing/dto/response/shared-folder-item.dto.ts
  src/modules/sharing/sharing.controller.ts
  src/modules/sharing/sharing.service.ts
Labels: ready-for-preview

#659 [_] fix(file-tests): fix file tests missed await
  src/modules/file/file.usecase.spec.ts
  src/modules/workspaces/dto/reponse/workspace.dto.ts
  src/modules/workspaces/workspaces.module.ts
Labels: bug

#673 [_] chore(deps): upgrade internxt lib version
  package.json
  yarn.lock
Labels: dependencies, ready-for-preview

#674 [PB-4830] chore/update deps
  package.json
  yarn.lock
Labels: dependencies, ready-for-preview

#668 [PB-2394] feat: calculate yesterday usage and first usage on first /usage call
  src/lib/time.ts
  src/modules/file/file.module.ts
  src/modules/file/file.repository.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/usage/usage.repository.spec.ts
  src/modules/usage/usage.repository.ts
  src/modules/usage/usage.service.spec.ts
  src/modules/usage/usage.service.ts
Labels: enhancement, ready-for-preview

#678 [_] fix(usage): prevent first and yesterday usage duplicated calculation
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/usage/usage.repository.spec.ts
  src/modules/usage/usage.repository.ts
  src/modules/usage/usage.service.spec.ts
  src/modules/usage/usage.service.ts
Labels: ready-for-preview

#680 [_] fix(usage): use find or create for usage
  src/modules/usage/usage.service.spec.ts
  src/modules/usage/usage.service.ts
Labels: bug, ready-for-preview

#682 [_] Fix/usage creation
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/usage/usage.repository.ts
  src/modules/usage/usage.service.spec.ts
  src/modules/usage/usage.service.ts
Labels: bug, ready-for-preview

#679 [_] fix(usage): add unique constraint to usage table
  migrations/20250825221935-create-user_id-period-type-partial-constraint.js
Labels: bug, ready-for-preview

#683 [_] refactor(time): use dayjs for better date operations
  src/lib/time.ts
Labels: ready-for-preview, refactor

#686 [_]: fix/remove-api-from-swagger-endpoints
  src/main.ts
Labels: enhancement, ready-for-preview

#687 [_]: fix/correct-invalid-whitespace
  src/modules/sharing/dto/create-sharing.dto.ts
Labels: bug, ready-for-preview

#688 [PB-4227] fix: files and folders with empty plainName are now movable
  src/modules/file/file.domain.ts
  src/modules/file/file.usecase.spec.ts
  src/modules/file/file.usecase.ts
  src/modules/folder/folder.controller.spec.ts
  src/modules/folder/folder.controller.ts
  src/modules/folder/folder.usecase.spec.ts
  src/modules/folder/folder.usecase.ts
  test/fixtures.ts
Labels: bug, ready-for-preview
